const f=document.getElementById('fileInput'),e=document.getElementById('editor'),c=document.getElementById('canvas'),x=c.getContext('2d',{willReadFrequently:true}),b=document.getElementById('brushSize'),p=document.getElementById('pixelSize'),u=document.getElementById('undoBtn'),cl=document.getElementById('clearBtn'),s=document.getElementById('saveBtn');let original=null,h=[],drawing=false,last=null;
f.onchange=async ev=>{const file=ev.target.files?.[0];if(!file)return;const img=await createImageBitmap(file);let w=img.width,hh=img.height,scale=Math.min(1,2400/Math.max(w,hh));w=Math.round(w*scale);hh=Math.round(hh*scale);c.width=w;c.height=hh;x.drawImage(img,0,0,w,hh);original=x.getImageData(0,0,w,hh);h=[];e.classList.remove('hidden')};
function pt(ev){const r=c.getBoundingClientRect();return{x:(ev.clientX-r.left)*c.width/r.width,y:(ev.clientY-r.top)*c.height/r.height}}
function hist(){h.push(x.getImageData(0,0,c.width,c.height));if(h.length>12)h.shift()}
function mosaic(cx,cy){const rad=+b.value/2,block=+p.value,src=original.data,img=x.getImageData(0,0,c.width,c.height),dst=img.data;for(let by=Math.max(0,Math.floor(cy-rad));by<Math.min(c.height,Math.ceil(cy+rad));by+=block){for(let bx=Math.max(0,Math.floor(cx-rad));bx<Math.min(c.width,Math.ceil(cx+rad));bx+=block){const sx=Math.min(c.width-1,Math.floor(bx+block/2)),sy=Math.min(c.height-1,Math.floor(by+block/2)),si=(sy*c.width+sx)*4;for(let yy=by;yy<Math.min(by+block,c.height);yy++){for(let xx=bx;xx<Math.min(bx+block,c.width);xx++){if(Math.hypot(xx-cx,yy-cy)>rad)continue;const di=(yy*c.width+xx)*4;dst[di]=src[si];dst[di+1]=src[si+1];dst[di+2]=src[si+2];dst[di+3]=src[si+3]}}}}x.putImageData(img,0,0)}
c.onpointerdown=ev=>{if(!original)return;drawing=true;c.setPointerCapture(ev.pointerId);hist();last=pt(ev);mosaic(last.x,last.y)};
c.onpointermove=ev=>{if(!drawing)return;const q=pt(ev),d=Math.hypot(q.x-last.x,q.y-last.y),step=Math.max(3,+b.value/5),n=Math.max(1,Math.ceil(d/step));for(let i=1;i<=n;i++){const t=i/n;mosaic(last.x+(q.x-last.x)*t,last.y+(q.y-last.y)*t)}last=q};
c.onpointerup=c.onpointercancel=()=>{drawing=false;last=null};
u.onclick=()=>{const q=h.pop();if(q)x.putImageData(q,0,0)};
cl.onclick=()=>{if(original){h=[];x.putImageData(original,0,0)}};
s.onclick=async()=>{const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.95));const file=new File([blob],'mosaic.jpg',{type:'image/jpeg'});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'モザイク画像'});return}catch{}}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mosaic.jpg';a.click();URL.revokeObjectURL(url)};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));